### ISSUE TITLE
Versioning incorrect

### ISSUE THREAD

**Issue by onyxnz** [backdrop-contrib/preset#18]
Hi Laryn
the info file needs updating to reflect the correct versioning of 2.02 now. The Video Embed Field module requires it at 2.02, and so update fails, as the Preset is not at 2.02 according to it's info file.

**Comment by laryn** [comment]
@onyxnz You should be able to  use this version at this point: https://github.com/backdrop-contrib/preset/releases/tag/1.x-2.0.2 

Let me know if you are still having trouble.
