### ISSUE TITLE
Use `theme_label_machine_name()` for the first column on the listing page

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/preset#2]
I am trying to reproduce a listing page from a Drupal 7 ctools export plugin implementation, and in that case the machine name was the second column on the listing page. For Backdrop, I think it should appear in the first column instead, but using `theme_label_machine_name()`  to be inline with the other admin interfaces in core. 

I'd like to recommend we do this automatically for all presets.

**Comment by jenlampton** [comment]
I've created a PR at https://github.com/backdrop-contrib/preset/pull/3 which switches to the theme function. It also sanitizes the label, which I don't think was done before. This change does remove the edit link, but I think that's okay because `Edit` is the first option in the drop-button.

**Comment by ghost** [comment]
Nice, thanks! I removed a `dpm()` and fixed a bug (you had a `;` instead of a `,`), then merged.
