### ISSUE TITLE
Use "Configure" not "Edit" since presets are stored in config

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/preset#4]
While working on https://github.com/backdrop-contrib/preset/issues/2 I noticed that the Operation to change an existing Preset was `Edit`, which I expect matches the Drupal ctools interface. But in Backdrop, the word `Edit` indicates that the thing you are editing is saved in the database. `Configure` should be used when the thing is saved on configuration.

**Comment by ghost** [comment]
Thanks @jenlampton. I added an 'edit' menu callback back in and set it to redirect to 'configure', for backwards-compatibility. Merged now.

**Comment by jenlampton** [comment]
even better, ty!
